program: train/train_attention.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
parameters:
  emb_dim:
    values: [32, 64, 128]
  hid_dim:
    values: [32, 64, 128]
  dropout:
    values: [0.2, 0.3]
  beam_size:
    values: [1, 3]
  learning_rate:
    values: [0.001, 0.0005]
  batch_size:
    values: [32, 64]
