program: train/train_vanilla.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
parameters:
  emb_dim:
    values: [16, 32, 64, 256]
  enc_layers:
    values: [1, 2, 3]
  dec_layers:
    values: [1, 2, 3]
  hid_dim:
    values: [16, 32, 64, 256]
  cell_type:
    values: ["RNN", "GRU", "LSTM"]
  dropout:
    values: [0.2, 0.3]
  beam_size:
    values: [1, 3, 5]
  learning_rate:
    values: [0.001, 0.0005]
  batch_size:
    values: [32, 64]
